### ISSUE TITLE
How to use elmo embedding?

### ISSUE THREAD

**Issue by SlashChven** [HIT-SCIR/ELMoForManyLangs#11]
Hi, i try to dump elmo embedding to txt and hdf5 format file. But i find the file is so big!
In my valid data, about 7W sentences , txt file nearly 20G and hdf5 nearly 15G, how to use this file?

Thanks

**Comment by Oneplus** [comment]
We've restructed the project, so that you can use the embeddings programmatically. I believe it solves the over-sized file problem.  Please check.
