### ISSUE TITLE
Wrong!!

### ISSUE THREAD

**Issue by charlesfufu** [HIT-SCIR/ELMoForManyLangs#14]
![image](https://user-images.githubusercontent.com/33311822/47417079-c2a77780-d7a9-11e8-8190-30b72e19037e.png)

**Comment by Oneplus** [comment]
seems the problem is resulted from wrongly configured cnn_50_100_512_4096_sample. Please refer the `Set up the config_path` section in the readme

**Comment by charlesfufu** [comment]
> seems the problem is resulted from wrongly configured cnn_50_100_512_4096_sample. Please refer the `Set up the config_path` section in the readme

![image](https://user-images.githubusercontent.com/33311822/47422847-318acd80-d7b6-11e8-8b0f-1b98c8bf5be6.png)
按照文档里的要求改了

**Comment by Oneplus** [comment]
应该改成这样 `"config_path": "cnn_50_100_512_4096_sample.json"`

**Comment by charlesfufu** [comment]
> cnn_50_100_512_4096_sample.json

我用了中文的训练好的model也改成"config_path": "cnn_50_100_512_4096_sample.json"感觉不对吧

**Comment by charlesfufu** [comment]
> 应该改成这样 `"config_path": "cnn_50_100_512_4096_sample.json"`

请问最后输出的hdf5文件是什么，如果我想得到每个字符embedding改怎么操作？

**Comment by Oneplus** [comment]
不能运行的问题似乎已经解决了，所以我要关了这个issue。

关于每个字符的embedding，我理解你指的是cnn的character输入。如果是这样，elmo不提供相应接口，你需要hack进代码。

关于hdf5的问题，你可以参考文档输出txt格式的embedding
