### ISSUE TITLE
. and / are replaced

### ISSUE THREAD

**Issue by CheHaoKang** [HIT-SCIR/ELMoForManyLangs#15]
Hi, 

Thanks for maintenance.

Just curious about the reason that **.** and **/** are replaced with **$period$** and **$backslash$**.
[(https://github.com/HIT-SCIR/ELMoForManyLangs/blob/master/elmoformanylangs/gen_elmo.py)](https://github.com/HIT-SCIR/ELMoForManyLangs/blob/master/elmoformanylangs/gen_elmo.py)
Do they present any bad effects?

Sincerely.

**Comment by Oneplus** [comment]
Seems there are no follow-up questions. I will close this issue.
