### ISSUE TITLE
原版bilm-tf的训练问题

### ISSUE THREAD

**Issue by NLP-konic** [HIT-SCIR/ELMoForManyLangs#17]
您好，想对比一下您的工具包和原始allen-tf版elmo训练包的性能，但在使用它的工具包时，进行单元测试，报错:说另一程序正在使用，因此进程无法访问，不知您是否也遇到过，谢谢

**Comment by Oneplus** [comment]
这个我没有什么经验，因为问题与本项目不相关，所以我要关闭这个issue了。
