### ISSUE TITLE
Cannot load embedder

### ISSUE THREAD

**Issue by timpal0l** [HIT-SCIR/ELMoForManyLangs#19]
I installed ELMoForManyLangs as instructed with `python setup.py install` and downloaded a custom language (Swedish).

Extracted the files from the swedish language model to a folder called `elmo_sv`.

`from elmoformanylangs import Embedder` 
`e = Embedder('elmo_sv/')`

Error:

`FileNotFoundError: [Errno 2] No such file or directory: '/Users/yijialiu/work/projects/conll2018/models/word_elmo/cnn_50_100_512_4096_sample.json'`

Something seems to be hardcoded to the user `yijialiu` - thats not me!

**Comment by NotToday** [comment]
Read chapter "Set up the config_path" in README. 
And file 'cnn_50_100_512_4096_sample.json' is in the "configs" folder.

**Comment by timpal0l** [comment]
My bad, it works now...

Off-topic. This embedding has 17 layers, in the allennlp implementation it has only 3. Is there any information what those 17 layers represent?
