### ISSUE TITLE
How to use the weights for chinese text classification? 

### ISSUE THREAD

**Issue by Jiakui** [HIT-SCIR/ELMoForManyLangs#2]
Can you give an example? 

Thanks~

**Comment by liuliuliuhuan** [comment]
> Can you give an example?
> 
> Thanks~

Have you successfully used this pre-training model in your classification task?

**Comment by Jorigorn** [comment]
Mybe put a SVM or other classifiers on top of a ELMo sentence representation as word2vec.
I will also experiment with this, perhaps update here later.

**Comment by Oneplus** [comment]
You can use it in the same way as word2vec embedding. Hope it help!
