### ISSUE TITLE
cuda out of memory

### ISSUE THREAD

**Issue by NotToday** [HIT-SCIR/ELMoForManyLangs#25]
在使用简体中文模型时，单句稍微长一点，或者batch大一点，就会报这个错误。
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524584710464/work/aten/src/THC/generic/THCStorage.c
即使把CUDA_VISIBLE_DEVICES开到多卡也会报错，感觉上不是模型太大的缘故

**Comment by huntzhan** [comment]
@NotToday 有在 `nvidia-smi` 上观察过显存占用吗？

**Comment by CathySha** [comment]
@NotToday 我也遇到了cuda out of memory这个问题，请问你是怎么解决的？

**Comment by CathySha** [comment]
@Oneplus 谢谢你的回复。另外还想问一下，你说的最大句子长度（20）和batch_size(32)中20和32这2个数字是一般建议的大小嘛？感觉句子最大长度是20的话有点短啊
