### ISSUE TITLE
Help Provide The Original Training Commands

### ISSUE THREAD

**Issue by huntzhan** [HIT-SCIR/ELMoForManyLangs#26]
@Oneplus Thanks for your great work! I wonder if you could share the *original commands* for training, especially for the training of `simplified-Chinese ELMo` model?

> ## Training Your Own ELMo
> Please run 
> ```
> python -m elmoformanylangs.biLM train -h
> ```

**Comment by Oneplus** [comment]
readme was updated, please check.

**Comment by huntzhan** [comment]
Thanks for the update! Do you use the same hyperparameter settings for all different languages? If not, wonder if you could provide the one used to train `simplified-Chinese ELMo`?

**Comment by Oneplus** [comment]
We use the same hyper-parmeters for all languages.

**Comment by huntzhan** [comment]
thanks!
