### ISSUE TITLE
Getting all layers

### ISSUE THREAD

**Issue by Nuccy90** [HIT-SCIR/ELMoForManyLangs#31]
Hi,

I was wondering whether there is a simple way to modify your code to return the 3 layers of the biLSTM, as in Peters et al. (2018), so as to train the task specific weights for the weighted average. 

Thank you

**Comment by strubell** [comment]
It looks like it would be pretty easy to modify `sents2elmo` in `elmo.py` here: https://github.com/HIT-SCIR/ELMoForManyLangs/blob/3ca013ff544ed50ed81acee83d4e0b98bc74926c/elmoformanylangs/elmo.py#L204

**Comment by strubell** [comment]
I just made (and tested) the change, it's in my fork: https://github.com/strubell/ELMoForManyLangs

running `e.sents2elmo(sents, output_layer=-2)` will return all three embeddings for each token.

Happy to submit a PR if the owners are interested.

**Comment by Oneplus** [comment]
@strubell Thanks! a PR will be welcome!

**Comment by strubell** [comment]
Submitted. PR #39 should resolve this issue.

**Comment by Oneplus** [comment]
@strubell Great! many thanks! Hopefully, this issue is resolved and I will close it.

**Comment by strubell** [comment]
Great! Thanks for releasing these models and code, they're a wonderful
multilingual resource!
