### ISSUE TITLE
Is it necessary to add <BOS> <EOS> tokens ? 

### ISSUE THREAD

**Issue by ereday** [HIT-SCIR/ELMoForManyLangs#34]
Hi, 
While using ELMoForManyLangs programmatically, do I need to add ```<bos> <eos>``` tokens manually to the sentences ? Specifically, could you specify which one of the below usages is the correct one ? 
```
from elmoformanylangs import Embedder

# Option-1 
e = Embedder('/path/to/your/model/')
sents = [['this','is','the','first','sentence'],['another','sentence']]
e.sents2elmo(sents)

#Option-2
e = Embedder('/path/to/your/model/')
sents = [['<bos>','this','is','the','first','sentence','<eos>'],['<bos>','another','sentence','<eos>']]
e.sents2elmo(sents)
```

**Comment by voidism** [comment]
No. It will add <eos> and <bos> automatically. You can find it in line 33 of `elmo.py`.
