### ISSUE TITLE
messing up eow_id and bow_id

### ISSUE THREAD

**Issue by experiencor** [HIT-SCIR/ELMoForManyLangs#38]
https://github.com/HIT-SCIR/ELMoForManyLangs/blob/f58684904dce11104581d19c318b0426fad7a764/elmoformanylangs/biLM.py#L111

I think it should be:
`eow_id, bow_id, oov_id, pad_id`

**Comment by Oneplus** [comment]
Thanks! It's our mistake. Semantically it should be `eow_id, bow_id`. However, considering our released models were trained on the wrong code. We have to stick to the wrong name. And I will close this issue.
