### ISSUE TITLE
I can not download the Japanese model

### ISSUE THREAD

**Issue by tanaka-jp** [HIT-SCIR/ELMoForManyLangs#4]
An error occurred while downloading the Japanese model of this url.
   http://pbmpb9h15.bkt.gdipper.com/ja.model.tar.xz

Can you check it ?

Thanks.

**Comment by Jorigorn** [comment]
Hi, I tried, no problem with the link, I can download the file:


wget http://pbmpb9h15.bkt.gdipper.com/ja.model.tar.xz
--2018-09-17 18:30:50--  http://pbmpb9h15.bkt.gdipper.com/ja.model.tar.xz
Resolving pbmpb9h15.bkt.gdipper.com (pbmpb9h15.bkt.gdipper.com)... 195.27.31.223, 195.27.31.222, 195.27.31.253, ...
Connecting to pbmpb9h15.bkt.gdipper.com (pbmpb9h15.bkt.gdipper.com)|195.27.31.223|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 420920380 (401M) [application/x-xz]
Saving to: 'ja.model.tar.xz'
23% [=====================================================>

**Comment by Oneplus** [comment]
Thanks for your interest and sorry for late reply.

We have an imperfect solution as mentioned in #5. If you still have problems with downloading the model, please comment in that issue.
