### ISSUE TITLE
如何在分类任务中使用ELMo

### ISSUE THREAD

**Issue by tsungruihon** [HIT-SCIR/ELMoForManyLangs#41]
您好，我现在已经下载了中文简体的ELMo模型，并且执行了该github页面的一些基本操作。
但是我不太了解如何用`pytorch`把`ELMo`预训练模型用在后续分类任务中，我看了一些`issue`说可以参考`word2vec`的应用方法，但是`word2vec`是静态词向量，而且我还看到部分`issue`说目前HIT的ELMo无法和`allennlp`结合使用。

因此您方便提供一些Pytorch使用例子吗？感激不尽。

**Comment by Biaocsu** [comment]
@tsungruihon  您好，我也下载了中文简体ELMo模型，但是哈工大仅提供安装包，我不知道后续该怎样生成词向量文件？另外生成的词向量文件用法是跟word2vec一样吗，你测试的效果怎样？可否提供例子供参考，不胜感激

**Comment by tsungruihon** [comment]
@Biaocsu 嗯嗯 其实你下载的中文简体ELMo模型就是一个词向量文件了 你只需要通过哈工大提供的接口就可以生成词向量了。

**Comment by Biaocsu** [comment]
@tsungruihon  有一点我不确定的是哈工大readme.md文件说数据需处理成conllu形式，我现在有20w个txt文件，感觉这样处理不合理，可能我理解错了，你可以再说明下数据格式吗？

**Comment by Biaocsu** [comment]
@tsungruihon  或者您可否分享一份你的代码给我参考下，哈哈哈，先谢谢啊！我的邮箱biaocsu@csu.edu.cn

**Comment by tsungruihon** [comment]
@Biaocsu 不需要整理`conllu`格式的 txt也可以的。
