### ISSUE TITLE
tokenization and fine tuning for Japanese

### ISSUE THREAD

**Issue by anz9990** [HIT-SCIR/ELMoForManyLangs#42]
How do I use Japanese ELMo on my own corpus? In the paper it is indicated that SCIR tokenizer is used. Is there a script provided for this? Also would like to fine-tune the model towards my corpus. What is the best way to do this?

**Comment by Oneplus** [comment]
@anz9990 We used the official raw data, which are preprocessed by udpipe. So you can use udpipe for Japanese word segmentation.

For fine-tuning, you can write your own model based on https://github.com/HIT-SCIR/ELMoForManyLangs/blob/master/elmoformanylangs/frontend.py#L160 and load the pretrained model with load_model.

**Comment by anz9990** [comment]
Thank you for your help!
