### ISSUE TITLE
英语的模型有点奇怪

### ISSUE THREAD

**Issue by lifengjin** [HIT-SCIR/ELMoForManyLangs#49]
我用好几种语言的预训练模型来跑自己的模型，效果都非常好，获得了非常大的性能提升，但是英语的模型不行，获得了非常大的性能下降。这有什么说法吗？

**Comment by Oneplus** [comment]
您可以试试allennlp的英语模型，我们训练模型的数据量比较小。

**Comment by lifengjin** [comment]
为什么其他的，比如德语的就特别好呢。。
