### ISSUE TITLE
Unable to download pretrained models

### ISSUE THREAD

**Issue by stefanknegt** [HIT-SCIR/ELMoForManyLangs#5]
First of all thanks for making this repo! However, when I try to download a pre-trained model, the download quits halfway since the connection to the server is lost. Could you maybe host them somewhere else? Thanks!

**Comment by Oneplus** [comment]
Sorry for late reply.

Since it is difficult for us to pay the bill for cloud services out of China like AWS, we host our model on a Chinese cloud service. Unfortunately, it seems this solution is not so stable.

I've uploaded some of the models onto my google drive and I accepted the request for a certain language (like Spanish mentioned above). The link is here: https://drive.google.com/open?id=1-MIo4Myz3oeP9q8lEsXQZl7UcAiTfJA8

If you're interested in the model for some specific language, please comment on this issue.

My google drive cannot host all the models. So if you would like to help us out, please also comment on this issue 😀

**Comment by stefanknegt** [comment]
I would like to download the Dutch model.

**Comment by Oneplus** [comment]
@stefanknegt Dutch model has been uploaded. Please check.

**Comment by stefanknegt** [comment]
Thanks, I got it.

**Comment by KeremZaman** [comment]
I need the Turkish model, thanks in advance.

**Comment by Oneplus** [comment]
@KeremZaman Turkish is ready, please check.

**Comment by crarojasca** [comment]
Thanks

**Comment by oepen** [comment]
colleagues,

would you be interested in injecting these models into our on-line repository at

http://vectors.nlpl.eu/repository/

the repository is hosted by the norwegian national HPC services and has a long-term commitment to accessibility.

if this were an interesting option, we would need to arrange for us to retrieve all of the files once and collaborate on creating at least the minimum metadata required for inclusion in the NLPL repository.

best, oe

**Comment by Oneplus** [comment]
Dear Prof @oepen,

Thank you so much! That's a great option! We would definitely like to inject our models on your repository. The whole repo for models will take 18G disk space. Each one is about 400M. If it's OK, please let me know what we can help.

Best regards
Yijia

**Comment by oepen** [comment]
great; thanks for supporting this!  what will be the best way for us to obtain the files?  i tried downloading via the links on the GitHub page, but no success.  if you emailed me (oe@ifi.uio.no) your google account name, i could probably share sufficient drive space with you.  would you be able to upload the files then?  could you also provide the full names and email addresses of everyone who should be named in the ‘creator’ field of our metadata?

**Comment by Oneplus** [comment]
Thanks to Prof @oepen and other colleagues, now the models were moved to [ NLPL Vectors Repository](http://wiki.nlpl.eu/index.php/Vectors/home). I believe the downloading problem is solved now, so I will close this issue.

**Comment by voidism** [comment]
Hi @Oneplus . I want to download the Simple Chinese model, but found that the Simple Chinese model is not on NLPL Vectors Repository. And the link in README of the Simple Chinese model is still old and broken. Can you provide the Simple Chinese model? Thank you so much!

**Comment by helenHlz** [comment]
:) @Oneplus . I want to download the simplified-Chinese model, but two links are useless. Can you update the link ? Thanks a lot.
