### ISSUE TITLE
Add a license!

### ISSUE THREAD

**Issue by ekreutz** [HIT-SCIR/ELMoForManyLangs#69]
Guys, you should consider adding a license to this repository. Not having a license means that the original contributors have exclusive access: https://choosealicense.com/no-permission/
You've clearly put a great deal of work into this so if you want the community to benefit adding a license is crucial!

___

1. Add a license to the repo itself. Most easily, you'll do this by just adding a `LICENSE.md` file to the root of the repo. (just paste a common license into that file)

2. Add a license for the models, if you've in fact trained them yourself. You can do this by stating the model license in in the `README.md`.

Keep up the great work!

**Comment by tsteffek** [comment]
I second this. We would like to use your code for research purposes, but can't without a license.

**Comment by Oneplus** [comment]
Thank you guys. The `LICENSE` file was added.
