### ISSUE TITLE
Input file demonstration

### ISSUE THREAD

**Issue by CheHaoKang** [HIT-SCIR/ELMoForManyLangs#9]
Hi, 

Thanks for maintenance.

Could you provide an input file example?
Since in the README, the example doesn't explain itself well.
It is still hard for me to fit my input into the format.

Thanks.

**Comment by rico93** [comment]
> Hi,
> 
> Thanks for maintenance.
> 
> Could you provide an input file example?
> Since in the README, the example doesn't explain itself well.
> It is still hard for me to fit my input into the format.
> 
> Thanks.

For the training part， according to the training code. U can use "plain" style. Which is as following:

I 'm ok .

If i am not wrong, each token is separated  by  one space.  and one sentence per line

**Comment by Oneplus** [comment]
@CheHaoKang You can use

```
embedding = h5py_file.get("隨著 搜尋 引擎 以及 網路 論壇 的 發達 ， 許多 病友 發現 自己 生病 時 的 諮 詢對象 不再 僅止 於 朋友 、 家人 或是 醫生 ， 而是 上網 進行 相關 醫療 資料 搜尋 ， 以嘗試 獲得 疾病 相關 資訊 ， 以便 能 早日 治療 疾病 。")
```

Actually, you need to use the whole sentence as input.

You also need to segment the document to get sentences as input.

**Comment by CheHaoKang** [comment]
Thanks for explanation.

Another question is **the shape of one sentence is (1, 1024)**.
Compared to the [original ELMo](https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md), the shape of one sentence is **(3, 16, 1024)**.
I understand **3 represents 3 layers** and **16 means separate tokens**.

Is it possible to retrieve the same result when using **HIT-SCIR/ELMoForManyLangs**?

Thanks for your patience.

**Comment by zaczou** [comment]
> Thanks for explanation.
> 
> Another question is **the shape of one sentence is (1, 1024)**. https://i.imgur.com/MXXipTb.png
> Compared to the [original ELMo](https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md), the shape of one sentence is **(3, 16, 1024)**.
> I understand **3 represents 3 layers** and **16 means separate tokens**. https://i.imgur.com/IaqW4dY.png
> 
> Is it possible to retrieve the same result when using **HIT-SCIR/ELMoForManyLangs**?
> 
> Thanks for your patience.

I also have the same question about the shape of one sentence (1, 1024).

**Comment by rico93** [comment]
> > Thanks for explanation.
> > Another question is **the shape of one sentence is (1, 1024)**. https://i.imgur.com/MXXipTb.png
> > Compared to the [original ELMo](https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md), the shape of one sentence is **(3, 16, 1024)**.
> > I understand **3 represents 3 layers** and **16 means separate tokens**. https://i.imgur.com/IaqW4dY.png
> > Is it possible to retrieve the same result when using **HIT-SCIR/ELMoForManyLangs**?
> > Thanks for your patience.
> 
> I also have the same question about the shape of one sentence (1, 1024).

According to the code gen_elmo.py 429-432, the reason is when u use '--output_layer -1', the code will average the model output.

**Comment by CheHaoKang** [comment]
Thanks for your explanantion.

Another question is **"is it possible to keep every token's vector?"**
Like the [original ELMo](https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md), the shape of one sentence is **(3, 16, 1024)** where **3 represents 3 layers and 16 means separate tokens**.
